### ISSUE TITLE
Please support mobile platform too

### ISSUE THREAD

**Issue by blacklightpy** [ianramzy/decentralized-video-chat#4]
I'm not a person who video calls often, but many of my friends do but they prefer to do it on mobile. Most of them have desktops without a webcam too which makes it difficult. The site works well when I check the switch to desktop mode. The camera quality is better in mobile too. In that case it doesn't make sense why it isn't supported on mobile by default and it would give a better experience if it can natively support mobile platform.

**Comment by joepio** [comment]
Since not all browsers support WebRTC p2p, the developer chose to disable it in all mobile browsers. Feature detection is probably a better approach. Maybe this library could help https://www.google.com/url?sa=t&source=web&rct=j&url=https://github.com/muaz-khan/DetectRTC&ved=2ahUKEwiJmJ692t7oAhVS3KQKHSU1ANwQFjABegQIARAB&usg=AOvVaw2uT88ATYVVh2cMZgEZwhlk

**Comment by roshnet** [comment]
@blacklightpy a quick workaround is to use the desktop version of the site. Worked for me.

**Comment by ianramzy** [comment]
So just to update you all: Android is currently working if you disable the redirect in chat.js, the CSS just needs to be fixed as well as remove some of the buttons. Its iOS that's the real problem. Specifically playing two videos at once (i.e. your own video and the other persons). If someone can figure out how to do two videos playing at once, that would be awesome!

**Comment by Chaphasilor** [comment]
Progress on mobile layout (Android for now) can be found in #7

**Comment by ianramzy** [comment]
Basic mobile support for Android and Safari on iOS is now complete.
